module.exports = {
  USER: "user_changed",
  DOCTOR: "doctor_changed",
  PATIENT: "patient_changed",
  APPOINTMENT: "appointment_changed",
  ADMISSION: "admission_changed",
  STAFF: "staff_changed",
  DEPARTMENT: "department_changed",
  ROOM: "room_changed",
  INVENTORY: "inventory_changed",
  OT: "ot_changed",
  WARD: "ward_changed",
  MEDICINE: "medicine_changed",
  TEST_MANAGEMENT: "test_management_changed",
  PATIENT_TEST: "patient_test_changed",
  TEST_RESULT: "test_result_changed",
  LAB_BILL: "lab_bill_changed",
  RADIOLOGY: "radiology_changed",
  CRITICAL: "critical_result_changed",
  REFUND: "refund_changed",
  EXPENSE: "expense_changed",
  SUMMARY: "summary_changed",
};
